spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ss_card?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type: trace
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  # 关闭Spring Security的默认登录页面
  security:
    basic:
      enabled: false

# 日志配置
logging:
  level:
    root: INFO
    com.example.membership: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.context: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080
  servlet:
    context-path: /

jwt:
  secret: your-secret-key-here-must-be-at-least-32-characters
  expiration: 86400000  # 24小时

aes:
  key: 12345678901234567890123456789012  # 32字节密钥

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.example.membership.controller



